---
- name: Check connectivity to remote servers
  hosts: all #servergroup01
  gather_facts: True
  tasks:
    - name: ping
      ping:
    - name: Print all available facts
      debug:
        var: ansible_facts
    - name: Print all available facts01
      ansible.builtin.debug:
        var: ansible_facts
