---
- name: Check connectivity to remote servers
  hosts: all #servergroup01
  tasks:
    - name: ping
      ping:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
